export const careerProfileDraftResponseSchema = {
  name: "career_profile_draft",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      summary: { type: "string" },
      skills: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            category: { type: "string" },
            items: { type: "array", items: { type: "string" } },
          },
          required: ["category", "items"],
        },
      },
      experience: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            title: { type: "string" },
            company: { type: "string" },
            location: { type: "string" },
            startDate: { type: "string" },
            endDate: { type: "string" },
            isCurrent: { type: "boolean" },
            description: { type: "string" },
            highlights: { type: "array", items: { type: "string" } },
          },
          required: [
            "title",
            "company",
            "location",
            "startDate",
            "endDate",
            "isCurrent",
            "description",
            "highlights",
          ],
        },
      },
      education: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            institution: { type: "string" },
            degree: { type: "string" },
            field: { type: "string" },
            location: { type: "string" },
            graduationDate: { type: "string" },
            highlights: { type: "array", items: { type: "string" } },
          },
          required: [
            "institution",
            "degree",
            "field",
            "location",
            "graduationDate",
            "highlights",
          ],
        },
      },
      projects: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            name: { type: "string" },
            description: { type: "string" },
            technologies: { type: "array", items: { type: "string" } },
            startDate: { type: "string" },
            endDate: { type: "string" },
            url: { type: "string" },
            highlights: { type: "array", items: { type: "string" } },
          },
          required: [
            "name",
            "description",
            "technologies",
            "startDate",
            "endDate",
            "url",
            "highlights",
          ],
        },
      },
      certifications: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            name: { type: "string" },
            issuer: { type: "string" },
            issueDate: { type: "string" },
            expirationDate: { type: "string" },
            credentialId: { type: "string" },
            url: { type: "string" },
          },
          required: [
            "name",
            "issuer",
            "issueDate",
            "expirationDate",
            "credentialId",
            "url",
          ],
        },
      },
      preferences: {
        type: "object",
        additionalProperties: false,
        properties: {
          targetRoles: { type: "array", items: { type: "string" } },
          industries: { type: "array", items: { type: "string" } },
          workModes: { type: "array", items: { type: "string" } },
          locations: { type: "array", items: { type: "string" } },
        },
        required: ["targetRoles", "industries", "workModes", "locations"],
      },
      additionalNotes: { type: "string" },
    },
    required: [
      "summary",
      "skills",
      "experience",
      "education",
      "projects",
      "certifications",
      "preferences",
      "additionalNotes",
    ],
  },
};
