export const careerProfileDraftResponseSchema = {
  name: "career_profile_draft",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      name: { type: "string" },
      focus: { type: "string" },
      headline: { type: "string" },
      summary: { type: "string" },
      careerGoals: { type: "string" },
      contactInfo: {
        type: "object",
        additionalProperties: false,
        properties: {
          email: { type: "string" },
          phone: { type: "string" },
          location: { type: "string" },
          links: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                label: { type: "string" },
                url: { type: "string" },
              },
              required: ["label", "url"],
            },
          },
        },
        required: ["email", "phone", "location", "links"],
      },
      additionalNotes: { type: "string" },
      experience: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            company: { type: "string" },
            title: { type: "string" },
            location: { type: "string" },
            startDate: { type: "string" },
            endDate: { type: "string" },
            isCurrent: { type: "boolean" },
            description: { type: "string" },
            achievements: { type: "string" },
          },
          required: [
            "company",
            "title",
            "location",
            "startDate",
            "endDate",
            "isCurrent",
            "description",
            "achievements",
          ],
        },
      },
      education: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            institution: { type: "string" },
            degree: { type: "string" },
            fieldOfStudy: { type: "string" },
            startDate: { type: "string" },
            endDate: { type: "string" },
            notes: { type: "string" },
          },
          required: [
            "institution",
            "degree",
            "fieldOfStudy",
            "startDate",
            "endDate",
            "notes",
          ],
        },
      },
      skills: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            name: { type: "string" },
            category: { type: "string" },
            proficiency: { type: "string" },
            evidence: { type: "string" },
          },
          required: ["name", "category", "proficiency", "evidence"],
        },
      },
      projects: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            name: { type: "string" },
            role: { type: "string" },
            description: { type: "string" },
            outcomes: { type: "string" },
            technologies: { type: "string" },
            link: { type: "string" },
            startDate: { type: "string" },
            endDate: { type: "string" },
          },
          required: [
            "name",
            "role",
            "description",
            "outcomes",
            "technologies",
            "link",
            "startDate",
            "endDate",
          ],
        },
      },
      certifications: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            name: { type: "string" },
            issuer: { type: "string" },
            issueDate: { type: "string" },
            expirationDate: { type: "string" },
            credentialId: { type: "string" },
            credentialUrl: { type: "string" },
            notes: { type: "string" },
          },
          required: [
            "name",
            "issuer",
            "issueDate",
            "expirationDate",
            "credentialId",
            "credentialUrl",
            "notes",
          ],
        },
      },
      preferences: {
        type: "object",
        additionalProperties: false,
        properties: {
          targetRoles: { type: "string" },
          targetIndustries: { type: "string" },
          locations: { type: "string" },
          workModes: { type: "string" },
          compensationGoals: { type: "string" },
          constraints: { type: "string" },
        },
        required: [
          "targetRoles",
          "targetIndustries",
          "locations",
          "workModes",
          "compensationGoals",
          "constraints",
        ],
      },
    },
    required: [
      "name",
      "focus",
      "headline",
      "summary",
      "careerGoals",
      "contactInfo",
      "additionalNotes",
      "experience",
      "education",
      "skills",
      "projects",
      "certifications",
      "preferences",
    ],
  },
};
